name: Publish package to the Maven Central Repository

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Maven Central Repository
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '11'
        cache: 'maven'
        server-id: ossrh
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
        gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
        gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}
    # We name releases v1.2.3 but Maven wants 1.2.3
    - id: get_version
      uses: baileyherbert/version-action@v3
    - if: github.event.release
      name: Update version in pom.xml (Release only)
      run: mvn -B versions:set -DnewVersion=${{ steps.get_version.outputs.version-without-v }} -DgenerateBackupPoms=false
    - name: Publish package
      run: mvn -B -Pdeploy -Dgpg.passphrase=${{ secrets.GPG_PASSPHRASE }} deploy
      env:
        MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}

# See https://itnext.io/publishing-artifacts-to-maven-central-using-github-actions-a-step-by-step-guide-fd65ef075fd4
# See https://docs.github.com/en/actions/publishing-packages/publishing-java-packages-with-maven
